name: Lint

on:
    push:
        branches: [ YOUR_BRANCH_NAME ]
    pull_request:

jobs:
    duster:
        name: Duster Lint

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: YOUR_PHP_VERSION
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --ignore-platform-reqs

            - name: Duster Lint
              run: vendor/bin/duster
